# NUMPY

NumPy is a Python library used for working with arrays.
It also has functions for working in linear algebra, fourier transform, and matrices.
NumPy stands for Numerical Python.

In [1]:
import numpy
a1 = numpy.array([1, 2, 3, 4, 5])
print(a1)

[1 2 3 4 5]


In [2]:
a1 = numpy.array(1, 2, 3, 4, 5)
print(a1)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [3]:
a1 = numpy.array(1)
print(a1)

1


In [4]:
a1 = numpy.array('Cat')
print(a1)

Cat


In [5]:

a2 = np.array([1, 2, 3, 4, 5])

print(a2)

NameError: name 'np' is not defined

In [6]:
import numpy as np
a2 = np.array([1, 2, 3, 4, 5])

print(a2)

[1 2 3 4 5]


In [7]:
#The array object in NumPy is called ndarray.
#We can create a NumPy ndarray object by using the array() function.


arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:

arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.



In [9]:

arr=np.array(10)
print(arr)
print(type(arr))

10
<class 'numpy.ndarray'>


In [10]:

a=np.array('Apple')
b=np.array("Ball")
print(a)
print(b)

Apple
Ball


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.



In [11]:

arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [12]:

arr=np.array(['a,b,c,d'])
a=np.array(["a,b,c,d"])
print(arr)
print(a)

['a,b,c,d']
['a,b,c,d']


In [13]:
arr=np.array(['a','b','c','d'])
print(arr)

['a' 'b' 'c' 'd']


# 2-D Arrays


These are often used to represent matrix.

In [14]:

arr=np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:

a=np.array([["a,b,c"],["d,e,f"]])
print(a)

[['a,b,c']
 ['d,e,f']]


In [16]:

a=np.array([[1,2,3]])
b=np.array([["a,b,c,d"]])
print(a)
print(b)
print(type(b))

[[1 2 3]]
[['a,b,c,d']]
<class 'numpy.ndarray'>


# 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.



In [17]:

arr=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Number of Dimensions
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.



In [18]:

a=np.array(10)
b=np.array([1, 2, 3, 4, 5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, we can define the number of dimensions by using the 'ndmin' argument.



In [19]:

a=np.array([1, 2, 3, 4], ndmin=5)
print(a)
print('No of dimensions :', a.ndim)

[[[[[1 2 3 4]]]]]
No of dimensions : 5


In [20]:
b=np.array(['a', 'b', 'c', 'd'], ndmin=3)
print(b)
print('No of dimensions :', b.ndim)

[[['a' 'b' 'c' 'd']]]
No of dimensions : 3


In [21]:
c=np.array([[[1,2,3]]])
print(c)
print(c.ndim)

[[[1 2 3]]]
3


In [22]:
d=np.array([[[[[[1,2,3]]]]]])
print(d)
print(d.ndim)

[[[[[[1 2 3]]]]]]
6
